tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-tint": "#7b4998",
                "on-secondary-container": "#75623f",
                "error-container": "#ffdad6",
                "on-primary-container": "#f7deff",
                "outline": "#7e7480",
                "surface-dim": "#dadada",
                "on-secondary-fixed-variant": "#554424",
                "on-secondary-fixed": "#261901",
                "surface-container-highest": "#e2e2e2",
                "primary-fixed-dim": "#e6b4ff",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#2f3131",
                "soft-lilac": "#F8F4FA",
                "primary-container": "#8452a1",
                "background": "#f9f9f9",
                "tertiary-container": "#666c00",
                "surface-container": "#eeeeee",
                "surface": "#f9f9f9",
                "surface-container-high": "#e8e8e8",
                "primary-fixed": "#f5d9ff",
                "surface-variant": "#e2e2e2",
                "on-tertiary-fixed-variant": "#464a00",
                "tertiary-fixed": "#e2ea79",
                "primary": "#6a3987",
                "inverse-primary": "#e6b4ff",
                "on-tertiary-fixed": "#1b1d00",
                "on-error-container": "#93000a",
                "secondary-container": "#fadfb3",
                "on-primary": "#ffffff",
                "secondary": "#6f5c39",
                "tertiary-fixed-dim": "#c6cd61",
                "on-surface-variant": "#4c444f",
                "surface-container-low": "#f3f3f4",
                "error": "#ba1a1a",
                "on-surface": "#1a1c1c",
                "surface-bright": "#f9f9f9",
                "outline-variant": "#cfc3d0",
                "warm-ivory": "#FFFDF9",
                "on-primary-fixed-variant": "#61317e",
                "deep-onyx": "#000000",
                "on-primary-fixed": "#30004a",
                "on-background": "#1a1c1c",
                "tertiary": "#4e5300",
                "inverse-on-surface": "#f0f1f1",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#fadfb3",
                "on-tertiary-container": "#e6ee7d",
                "on-error": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#dcc399"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "section-padding-sm": "64px",
                "unit": "8px",
                "gutter": "24px",
                "section-padding-lg": "120px",
                "container-max-width": "1200px"
            },
            "fontFamily": {
                "display-lg": ["Bodoni Moda"],
                "headline-lg-mobile": ["Bodoni Moda"],
                "body-md": ["Hanken Grotesk"],
                "display-md": ["Bodoni Moda"],
                "body-lg": ["Hanken Grotesk"],
                "label-caps": ["Hanken Grotesk"],
                "headline-lg": ["Bodoni Moda"],
                "accent-text": ["Playfair Display"]
            },
            "fontSize": {
                "display-lg": ["72px", { "lineHeight": "84px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
                "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
                "body-md": ["20px", { "lineHeight": "24px", "fontWeight": "400" }],
                "display-md": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-caps": ["16px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
                "headline-lg": ["40px", { "lineHeight": "48px", "fontWeight": "400" }],
                "accent-text": ["24px", { "lineHeight": "32px", "fontWeight": "400" }]
            }
        }
    }
};
